version: '3.8'

services:
  web:
    build: .
    container_name: myapp_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: myapp_db
    environment:
      MYSQL_DATABASE: vitala
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db_data:
